# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_add_player_3_kuvat.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from modify import *


class Ui_MainWindow(object):
    def newPlayer(self):
        self.juomarit = lisaa_pelaaja(self.juomarit, self.playerName.text())
        print(self.juomarit[len(self.juomarit)-1].name)
        self.InitialDrinkPage.show()
        self.InitialPlayerPage.hide()
        self.comboBox.addItem(self.juomarit[len(self.juomarit)-1].name)

    def newDrink(self):
        playername = self.comboBox.currentText()
        drink = self.lineEdit.text()
        idx = 0
        for i in range(len(self.juomarit)):
            if self.juomarit[idx].name == playername:
                idx = i
        self.juomarit[idx].lisaa_juoma(drink)
        self.lineEdit.clear()
        print(self.juomarit[idx].juomalista)
    
    def pelaa_painettu(self):
        self.pelaa_wdg.show()
        for juomari in self.juomarit:
            self.comboBox.additem(juomari.name)
    
    def arvo_juoma(self):
        idx = 0
        for i in range(self.juomarit):
            if self.juomarit[i].name == self.pelaaja_menu.currentText():
                idx = i
        juomari = self.juomarit[idx]
        juomari, juoma = pelaa(juomari)
        self.juomarit[idx] = juomari
        self.print_juoma.setText(juoma)
    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.InitialPlayerPage = QtWidgets.QWidget()
        self.InitialPlayerPage.setObjectName("InitialPlayerPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.InitialPlayerPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kuva = QtWidgets.QLabel(self.InitialPlayerPage)
        self.kuva.setText("")
        self.kuva.setPixmap(QtGui.QPixmap("w5fi6.jpg"))
        self.kuva.setAlignment(QtCore.Qt.AlignCenter)
        self.kuva.setObjectName("kuva")
        self.verticalLayout.addWidget(self.kuva)
        self.label = QtWidgets.QLabel(self.InitialPlayerPage)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.playerName = QtWidgets.QLineEdit(self.InitialPlayerPage)
        self.playerName.setObjectName("playerName")
        self.verticalLayout.addWidget(self.playerName)
        self.addPlayer = QtWidgets.QPushButton(self.InitialPlayerPage)
        self.addPlayer.setObjectName("addPlayer")
        self.verticalLayout.addWidget(self.addPlayer)
        self.seuraava_btn = QtWidgets.QPushButton(self.InitialPlayerPage)
        self.seuraava_btn.setObjectName("seuraava_btn")
        self.verticalLayout.addWidget(self.seuraava_btn)
        self.stackedWidget.addWidget(self.InitialPlayerPage)
        self.InitialDrinkPage = QtWidgets.QWidget()
        self.InitialDrinkPage.setObjectName("InitialDrinkPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.InitialDrinkPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.kuva_2 = QtWidgets.QLabel(self.InitialDrinkPage)
        self.kuva_2.setText("")
        self.kuva_2.setPixmap(QtGui.QPixmap("beer-pic-1920x1080.jpg"))
        self.kuva_2.setScaledContents(False)
        self.kuva_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kuva_2.setObjectName("kuva_2")
        self.verticalLayout_3.addWidget(self.kuva_2)
        self.player_label = QtWidgets.QLabel(self.InitialDrinkPage)
        self.player_label.setObjectName("player_label")
        self.verticalLayout_3.addWidget(self.player_label)
        self.comboBox = QtWidgets.QComboBox(self.InitialDrinkPage)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.tableView = QtWidgets.QTableView(self.InitialDrinkPage)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.addDrink_label = QtWidgets.QLabel(self.InitialDrinkPage)
        self.addDrink_label.setObjectName("addDrink_label")
        self.verticalLayout_3.addWidget(self.addDrink_label)
        self.lineEdit = QtWidgets.QLineEdit(self.InitialDrinkPage)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.addDrink_btn = QtWidgets.QPushButton(self.InitialDrinkPage)
        self.addDrink_btn.setObjectName("addDrink_btn")
        self.verticalLayout_3.addWidget(self.addDrink_btn)
        self.jatka_btn = QtWidgets.QPushButton(self.InitialDrinkPage)
        self.jatka_btn.setObjectName("jatka_btn")
        self.verticalLayout_3.addWidget(self.jatka_btn)
        self.stackedWidget.addWidget(self.InitialDrinkPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.mainPage)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("dfb64d5864169d48834d81dd8a9d5df4.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pelaa_wdg = QtWidgets.QStackedWidget(self.mainPage)
        self.pelaa_wdg.setObjectName("pelaa_wdg")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pelaa_wdg.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.roll_btn = QtWidgets.QPushButton(self.page_2)
        self.roll_btn.setGeometry(QtCore.QRect(10, 180, 341, 23))
        self.roll_btn.setObjectName("roll_btn")
        self.print_juoma = QtWidgets.QLabel(self.page_2)
        self.print_juoma.setGeometry(QtCore.QRect(10, 20, 341, 91))
        self.print_juoma.setObjectName("print_juoma")
        self.pelaaja_menu = QtWidgets.QComboBox(self.page_2)
        self.pelaaja_menu.setGeometry(QtCore.QRect(10, 150, 69, 22))
        self.pelaaja_menu.setAccessibleDescription("")
        self.pelaaja_menu.setCurrentText("")
        self.pelaaja_menu.setObjectName("pelaaja_menu")
        self.valitse_pelaaja = QtWidgets.QLabel(self.page_2)
        self.valitse_pelaaja.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.valitse_pelaaja.setObjectName("valitse_pelaaja")
        self.tilastot_wdg = QtWidgets.QStackedWidget(self.page_2)
        self.tilastot_wdg.setGeometry(QtCore.QRect(-20, 0, 561, 451))
        self.tilastot_wdg.setObjectName("tilastot_wdg")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tilastot_tree_view = QtWidgets.QTreeView(self.page_3)
        self.tilastot_tree_view.setGeometry(QtCore.QRect(20, 0, 531, 411))
        self.tilastot_tree_view.setObjectName("tilastot_tree_view")
        self.juomalista_wdg = QtWidgets.QStackedWidget(self.page_3)
        self.juomalista_wdg.setGeometry(QtCore.QRect(20, 0, 541, 451))
        self.juomalista_wdg.setObjectName("juomalista_wdg")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.juoma_table_view = QtWidgets.QTableView(self.page_5)
        self.juoma_table_view.setGeometry(QtCore.QRect(0, 0, 521, 431))
        self.juoma_table_view.setObjectName("juoma_table_view")
        self.juomalista_wdg.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.juomalista_wdg.addWidget(self.page_6)
        self.tilastot_wdg.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tilastot_wdg.addWidget(self.page_4)
        self.pelaa_wdg.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.pelaa_wdg)
        self.pelaa_btn = QtWidgets.QPushButton(self.mainPage)
        self.pelaa_btn.setObjectName("pelaa_btn")
        self.verticalLayout_2.addWidget(self.pelaa_btn)
        self.tilastot_btn = QtWidgets.QPushButton(self.mainPage)
        self.tilastot_btn.setObjectName("tilastot_btn")
        self.verticalLayout_2.addWidget(self.tilastot_btn)
        self.lista_btn = QtWidgets.QPushButton(self.mainPage)
        self.lista_btn.setObjectName("lista_btn")
        self.verticalLayout_2.addWidget(self.lista_btn)
        self.lopeta_btn = QtWidgets.QPushButton(self.mainPage)
        self.lopeta_btn.setObjectName("lopeta_btn")
        self.verticalLayout_2.addWidget(self.lopeta_btn)
        self.stackedWidget.addWidget(self.mainPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionUusi_peli = QtWidgets.QAction(MainWindow)
        self.actionUusi_peli.setObjectName("actionUusi_peli")
        self.actionLopeta_peli = QtWidgets.QAction(MainWindow)
        self.actionLopeta_peli.setObjectName("actionLopeta_peli")
        self.menuFile.addAction(self.actionUusi_peli)
        self.menuFile.addAction(self.actionLopeta_peli)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.InitialPlayerPage.show()
        self.InitialDrinkPage.hide()
        self.mainPage.hide()
        self.addPlayer.clicked.connect(self.newPlayer)
        self.addDrink_btn.clicked.connect(self.newDrink)
        self.pelaa_btn.clicked.connect(self.pelaa_painettu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tervetuloa pelaamaan JUOMAPELIÄ!!!"))
        self.addPlayer.setText(_translate("MainWindow", "Lisää pelaaja"))
        self.seuraava_btn.setText(_translate("MainWindow", "Seuraava"))
        self.player_label.setText(_translate("MainWindow", "Valitse pelaaja"))
        self.addDrink_label.setText(_translate("MainWindow", "Syötä juoma:"))
        self.addDrink_btn.setText(_translate("MainWindow", "Lisää juoma"))
        self.jatka_btn.setText(_translate("MainWindow", "Seuraava"))
        self.roll_btn.setText(_translate("MainWindow", "Arvo juoma"))
        self.print_juoma.setText(_translate("MainWindow", "TextLabel"))
        self.valitse_pelaaja.setText(_translate("MainWindow", "Valitse pelaaja"))
        self.pelaa_btn.setText(_translate("MainWindow", "Pelaa"))
        self.tilastot_btn.setText(_translate("MainWindow", "Tilastot"))
        self.lista_btn.setText(_translate("MainWindow", "Juomalista"))
        self.lopeta_btn.setText(_translate("MainWindow", "Lopeta"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionUusi_peli.setText(_translate("MainWindow", "Uusi peli"))
        self.actionLopeta_peli.setText(_translate("MainWindow", "Lopeta peli"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
